program test1;
uses zeit,feiertag,stdio;
begin
   writeln(stopuhr('heute '));
   konvert_timestamp('22.02.2016 12:00:00,00');
   formate_moment(akt_moment);
   zeige_formate;
   loesche_alle_feiertage;
   if feiertage_bestimmen(2016) then writeln('FT OK') else writeln('™””');
   neuer_feiertag_nach_datum(8,2,'Blue Monday');
   feiertage_sortieren;
   zeige_alle_feiertage;
   konvert_timestamp('08.02.2016 11:11:11,11');
   feiertage_eintragen(akt_moment);
   formate_moment(akt_moment);
   zeige_formate;
   zeige_feiertage;
   konvert_timestamp('01.07.1966 00:42:17,98');
   formate_moment(akt_moment);
   zeige_formate;
   test_moment:=akt_moment;
   konvert_timestamp('01.07.2016 00:42:17,97');
   formate_moment(akt_moment);
   zeige_formate;
   differenz_moment;
   writeln(Diff_TimeStamp);
   writeln(Diff_TimeStamp24);
   writeln(Diff_Einzel);
   writeln(Diff_ABS);
   writeln(Diff_Abs_Sekunden);
   konvert_timestamp('10.02.2016 12:00:00,00');
   formate_moment(akt_moment);
   zeige_formate;
   writeln('plus 1 Jahr');
   test_moment:=akt_moment;
   addiere_moment(akt_moment,1,0,0,0,0,0,0);
   formate_moment(akt_moment);
   zeige_formate;
   differenz_moment;
   writeln(Diff_TimeStamp);
   writeln(Diff_TimeStamp24);
   writeln(Diff_Einzel);
   writeln(Diff_ABS);
   writeln(Diff_Abs_Sekunden);
   writeln('minus 346 Tage');
   akt_moment:=test_moment;
   addiere_moment(akt_moment,0,0,-346,0,0,0,0);
   formate_moment(akt_moment);
   zeige_formate;
   differenz_moment;
   writeln(Diff_TimeStamp);
   writeln(Diff_TimeStamp24);
   writeln(Diff_Einzel);
   writeln(Diff_ABS);
   writeln(Diff_Abs_Sekunden);
   writeln('minus 347 Tage');
   akt_moment:=test_moment;
   addiere_moment(akt_moment,0,0,-347,0,0,0,0);
   formate_moment(akt_moment);
   zeige_formate;
   differenz_moment;
   writeln(Diff_TimeStamp);
   writeln(Diff_TimeStamp24);
   writeln(Diff_Einzel);
   writeln(Diff_ABS);
   writeln(Diff_Abs_Jahre);
   writeln(Diff_Abs_Monate);
   writeln(Diff_Abs_Wochen);
   writeln(Diff_Abs_Tage);
   writeln(Diff_Abs_Stunden);
   writeln(Diff_Abs_Minuten);
   writeln(Diff_Abs_Sekunden);
end.
